---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность доступа к сайту с помощью выбора языка 
  - У пользователя должна быть возможность удалить товар из корзины
  - Пользователь должен иметь возможность возвращаться к списку товаров
  - У пользователя должна быть возможность убедиться, что товар добавен  в корзину
  - Пользователь должен иметь возможность  очистить корзину одним кликом
  - У пользователя должна быть возможность выйти из корзины и продолжить покупки
  - Пользователь должен иметь возможность оформить заказ
  
