---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Текст страницы должен переводиться в соответствии с выбранным языком
  - Денежные единицы должны изменяться при выборе языка
  - У пользователя должна быть возможность удалить товар из корзины
  - В выпадающем списке категории должна быть категория "Все товары" для возвращения всего списка товаров
  - При отмене выбора фильтра должен возвращаться весь список товаров
  - При добавлении товара в корзину, кнопка добавить должна изменить название на "В корзине" 
  - Пользователь должен иметь возможность  очистить корзину одним кликом
  - У пользователя должна быть возможность выйти из корзины и продолжить покупки
  - При просмотре описания товара в его карточке, должна быть стрелка "Вернуться к списку товаров"
  
